"""Demo metadata — keep in sync with web/lib/demos.ts."""

DEMOS = [
    {
        "slug": "pdf-qa",
        "title": "PDF QA Bot",
        "tagline": "Upload a PDF and ask grounded questions.",
        "phase": 1,
        "kind": "pdf",
        "github": "PDF%20QA%20Bot",
        "tags": ["RAG", "Chroma", "Gradio lab"],
    },
    {
        "slug": "sql-agent",
        "title": "Natural Language SQL Agent",
        "tagline": "Ask Chinook SQLite questions in English.",
        "phase": 1,
        "kind": "chat",
        "github": "Natural%20Language%20SQL%20Agent",
        "tags": ["SQL", "LangChain", "Tools"],
    },
    {
        "slug": "math-assistant",
        "title": "AI Math Assistant",
        "tagline": "ReAct math agent with Wikipedia tools.",
        "phase": 1,
        "kind": "chat",
        "github": "AI%20Math%20Assistant",
        "tags": ["LangGraph", "Tools"],
    },
    {
        "slug": "youtube-summarizer",
        "title": "YouTube Summarizer",
        "tagline": "Transcript → RAG summary and Q&A.",
        "phase": 1,
        "kind": "youtube",
        "github": "YouTube%20Summarizer",
        "tags": ["RAG", "FAISS"],
    },
    {
        "slug": "connoisseur",
        "title": "Connoisseur Companion",
        "tagline": "Multi-agent California dining recommendations.",
        "phase": 2,
        "kind": "chat",
        "github": "Connoisseur%20Companion",
        "tags": ["Multi-agent", "RAG", "MCP"],
    },
    {
        "slug": "docchat",
        "title": "DocChat",
        "tagline": "Relevance → research → verify over your docs.",
        "phase": 2,
        "kind": "docs",
        "github": "DocChat",
        "tags": ["LangGraph", "RAG"],
    },
    {
        "slug": "food-search",
        "title": "Food Search RAG",
        "tagline": "Chroma food retrieval plus LLM recommendations.",
        "phase": 2,
        "kind": "chat",
        "github": "Food%20Search%20RAG",
        "tags": ["RAG", "Chroma"],
    },
    {
        "slug": "icebreaker",
        "title": "Icebreaker Bot",
        "tagline": "Chat with a mock LinkedIn profile (RAG).",
        "phase": 2,
        "kind": "chat",
        "github": "Icebreaker%20Bot",
        "tags": ["LlamaIndex", "RAG"],
    },
    {
        "slug": "data-viz",
        "title": "Data Viz Agent",
        "tagline": "Pandas + matplotlib over student-mat.",
        "phase": 3,
        "kind": "chat",
        "github": "Data%20Viz%20Agent",
        "tags": ["pandas", "matplotlib"],
    },
    {
        "slug": "data-analysis",
        "title": "AI Powered Data Analysis",
        "tagline": "LangGraph agent over bundled CSVs.",
        "phase": 3,
        "kind": "chat",
        "github": "AI%20Powered%20Data%20Analysis",
        "tags": ["LangGraph", "pandas"],
    },
    {
        "slug": "style-finder",
        "title": "Style Finder",
        "tagline": "Match an outfit photo to a fashion catalog.",
        "phase": 3,
        "kind": "image",
        "github": "Style%20Finder",
        "tags": ["Vision", "ResNet"],
    },
    {
        "slug": "nutrition-coach",
        "title": "AI Nutrition Coach",
        "tagline": "Vision LLM calorie and nutrition notes.",
        "phase": 3,
        "kind": "image",
        "github": "AI%20Nutrition%20Coach",
        "tags": ["Vision", "Flask lab"],
    },
    {
        "slug": "model-compare",
        "title": "Model Comparison Chat",
        "tagline": "Three Groq slots, structured JSON replies.",
        "phase": 3,
        "kind": "compare",
        "github": "Model%20Comparison%20Chat",
        "tags": ["Groq", "JSON"],
    },
    {
        "slug": "nourishbot",
        "title": "NourishBot",
        "tagline": "CrewAI recipe or nutrition analysis from a photo.",
        "phase": 4,
        "kind": "image",
        "github": "NourishBot",
        "tags": ["CrewAI", "Vision"],
    },
    {
        "slug": "meal-planner",
        "title": "Meal Grocery Planner",
        "tagline": "CrewAI meal plan, shopping list, budget.",
        "phase": 4,
        "kind": "form",
        "github": "Meal%20Grocery%20Planner",
        "tags": ["CrewAI"],
    },
    {
        "slug": "healthcare",
        "title": "Healthcare Chatbot",
        "tagline": "Educational multi-agent consult — not medical care.",
        "phase": 4,
        "kind": "healthcare",
        "github": "Healthcare%20Chatbot",
        "tags": ["AutoGen", "Educational"],
    },
    {
        "slug": "meeting-assistant",
        "title": "Meeting Assistant",
        "tagline": "Whisper-tiny transcript → minutes and tasks.",
        "phase": 5,
        "kind": "audio",
        "github": "Meeting%20Assistant",
        "tags": ["Whisper", "Groq"],
    },
]
